DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "http://example.org/"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "Mluther"
title = "Mluther"
[[menu.main]]
identifier = "news"
name = "News"
title = "News section"
url = "/news/"
weight = -100
[[menu.main]]
identifier = "sermons"
name = "Sermons"
title = "Sermons section"
url = "/sermons/"
weight = -110
[params]
background_color_class = "bg-black"
description = "The last theme you'll ever need. Maybe."
facebook = ""
favicon = ""
featured_image = "/images/Scriptures.jpg"
github = ""
instagram = ""
linkedin = ""
recent_posts_number = 2
twitter = "https://twitter.com/MlutherMO"
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
