baseURL = "http://example.org/"
languageCode = "en-us"
title = "Mluther"
theme = "mluther"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/MlutherMO"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/Scriptures.jpg"
  recent_posts_number = 2

[menu]

  [[menu.main]]
    identifier = "sermons"
    name = "Sermons"
    title = "Sermons section"
    url = "/sermons/"
    weight = -110

  [[menu.main]]
    identifier = "news"
    name = "News"
    title = "News section"
    url = "/news/"
    weight = -100